const LocationEnum = {
    AN_GIANG: { query_location: "AnGiang", query_name: "An Giang" },
    BA_RIA_VUNG_TAU: { query_location: "BaRiaVungTau", query_name: "Bà Rịa - Vũng Tàu" },
    BAC_GIANG: { query_location: "BacGiang", query_name: "Bắc Giang" },
    BAC_KAN: { query_location: "BacKan", query_name: "Bắc Kạn" },
    BAC_LIEU: { query_location: "BacLieu", query_name: "Bạc Liêu" },
    BAC_NINH: { query_location: "BacNinh", query_name: "Bắc Ninh" },
    BEN_TRE: { query_location: "BenTre", query_name: "Bến Tre" },
    BINH_DINH: { query_location: "BinhDinh", query_name: "Bình Định" },
    BINH_DUONG: { query_location: "BinhDuong", query_name: "Bình Dương" },
    BINH_PHUOC: { query_location: "BinhPhuoc", query_name: "Bình Phước" },
    BINH_THUAN: { query_location: "BinhThuan", query_name: "Bình Thuận" },
    CA_MAU: { query_location: "CaMau", query_name: "Cà Mau" },
    CAN_THO: { query_location: "CanTho", query_name: "Cần Thơ" },
    CAO_BANG: { query_location: "CaoBang", query_name: "Cao Bằng" },
    DA_NANG: { query_location: "DaNang", query_name: "Đà Nẵng" },
    DAK_LAK: { query_location: "DakLak", query_name: "Đắk Lắk" },
    DAK_NONG: { query_location: "DakNong", query_name: "Đắk Nông" },
    DIEN_BIEN: { query_location: "DienBien", query_name: "Điện Biên" },
    DONG_NAI: { query_location: "DongNai", query_name: "Đồng Nai" },
    DONG_THAP: { query_location: "DongThap", query_name: "Đồng Tháp" },
    GIA_LAI: { query_location: "GiaLai", query_name: "Gia Lai" },
    HA_GIANG: { query_location: "HaGiang", query_name: "Hà Giang" },
    HA_NAM: { query_location: "HaNam", query_name: "Hà Nam" },
    HA_NOI: { query_location: "HaNoi", query_name: "Hà Nội" },
    HA_TINH: { query_location: "HaTinh", query_name: "Hà Tĩnh" },
    HAI_DUONG: { query_location: "HaiDuong", query_name: "Hải Dương" },
    HAI_PHONG: { query_location: "HaiPhong", query_name: "Hải Phòng" },
    HAU_GIANG: { query_location: "HauGiang", query_name: "Hậu Giang" },
    HOA_BINH: { query_location: "HoaBinh", query_name: "Hòa Bình" },
    HUNG_YEN: { query_location: "HungYen", query_name: "Hưng Yên" },
    KHANH_HOA: { query_location: "KhanhHoa", query_name: "Khánh Hòa" },
    KIEN_GIANG: { query_location: "KienGiang", query_name: "Kiên Giang" },
    KON_TUM: { query_location: "KonTum", query_name: "Kon Tum" },
    LAI_CHAU: { query_location: "LaiChau", query_name: "Lai Châu" },
    LAM_DONG: { query_location: "LamDong", query_name: "Lâm Đồng" },
    LANG_SON: { query_location: "LangSon", query_name: "Lạng Sơn" },
    LAO_CAI: { query_location: "LaoCai", query_name: "Lào Cai" },
    LONG_AN: { query_location: "LongAn", query_name: "Long An" },
    NAM_DINH: { query_location: "NamDinh", query_name: "Nam Định" },
    NGHE_AN: { query_location: "NgheAn", query_name: "Nghệ An" },
    NINH_BINH: { query_location: "NinhBinh", query_name: "Ninh Bình" },
    NINH_THUAN: { query_location: "NinhThuan", query_name: "Ninh Thuận" },
    PHU_THO: { query_location: "PhuTho", query_name: "Phú Thọ" },
    PHU_YEN: { query_location: "PhuYen", query_name: "Phú Yên" },
    QUANG_BINH: { query_location: "QuangBinh", query_name: "Quảng Bình" },
    QUANG_NAM: { query_location: "QuangNam", query_name: "Quảng Nam" },
    QUANG_NGAI: { query_location: "QuangNgai", query_name: "Quảng Ngãi" },
    QUANG_NINH: { query_location: "QuangNinh", query_name: "Quảng Ninh" },
    QUANG_TRI: { query_location: "QuangTri", query_name: "Quảng Trị" },
    SOC_TRANG: { query_location: "SocTrang", query_name: "Sóc Trăng" },
    SON_LA: { query_location: "SonLa", query_name: "Sơn La" },
    TAY_NINH: { query_location: "TayNinh", query_name: "Tây Ninh" },
    THAI_BINH: { query_location: "ThaiBinh", query_name: "Thái Bình" },
    THAI_NGUYEN: { query_location: "ThaiNguyen", query_name: "Thái Nguyên" },
    THANH_HOA: { query_location: "ThanhHoa", query_name: "Thanh Hóa" },
    THUA_THIEN_HUE: { query_location: "ThuaThienHue", query_name: "Thừa Thiên Huế" },
    TIEN_GIANG: { query_location: "TienGiang", query_name: "Tiền Giang" },
    TP_HO_CHI_MINH: { query_location: "HoChiMinh", query_name: "TP. Hồ Chí Minh" },
    TRA_VINH: { query_location: "TraVinh", query_name: "Trà Vinh" },
    TUYEN_QUANG: { query_location: "TuyenQuang", query_name: "Tuyên Quang" },
    VINH_LONG: { query_location: "VinhLong", query_name: "Vĩnh Long" },
    VINH_PHUC: { query_location: "VinhPhuc", query_name: "Vĩnh Phúc" },
    YEN_BAI: { query_location: "YenBai", query_name: "Yên Bái" },
    DEFAULT: { query_location : "", query_name : ""}
  };
  
  module.exports = LocationEnum;
  