name: Deploy WebCuoiKy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            set -e
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            echo "Pulling latest code..."
            cd /home/prod/cuoi-ky
            git reset --hard
            git pull origin main

            echo "Deploying Backend..."
            cd backend
            npm install
            pm2 startOrRestart ecosystem.config.js --name ServerExpress

            echo "Deploying Frontend..."
            cd ../frontend
            npm install
            npm run build
            pm2 startOrRestart ecosystem.config.cjs --name ReactVite

            echo "Deploy Complete!"
      - name: Notify Discord Success!
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"✅ **Deploy thành công** trên branch \`${{ github.ref_name }}\` bởi \`${{ github.actor }}\`\"}" \
            ${{ secrets.DISCORD_WEBHOOK }}
      - name: ❌ Notify Discord Failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"❌ **Deploy thất bại** trên branch \`${{ github.ref_name }}\` bởi \`${{ github.actor }}\`\"}" \
            ${{ secrets.DISCORD_WEBHOOK }}